<?php

namespace App\Models;

use Laravel\Sanctum\HasApiTokens;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;


class UsersModel extends Authenticatable
{
    use HasFactory , HasApiTokens ,Notifiable;
    protected $table = 'users';
    public $timestamps = false;
    protected $fillable = [
        'account_type',
        'address',
        'city',
        'country',
        'country_code',
        'created_at',
        'demo',
        'email',
        'email_verified',
        'hit',
        'image',
        'last_login',
        'layouts',
        'name',
        'password',
        'paypal_email',
        'paypal_payment',
        'paytabs_payment',
        'paytabs_profile_id',
        'paytabs_server_key',
        'phone',
        'postcode',
        'publish_key',
        'role',
        'secret_key',
        'slug',
        'state',
        'status',
        'stripe_payment',
        'thumb',
        'title',
        'trial_expire',
        'user_name',
        'user_type',
        'verify_code',
        'account_type',
        'address',
        'city',
        'country',
        'created_at',
        'email',
        'email_verified',
        'hit',
        'image',
        'last_login',
        'layouts',
        'name',
        'password',
        'paypal_email',
        'paypal_payment',
        'phone',
        'postcode',
        'publish_key',
        'role',
        'secret_key',
        'slug',
        'state',
        'status',
        'stripe_payment',
        'thumb',
        'title',
        'trial_expire',
        'user_name',
        'user_type',
        'verify_code',
        'CURRENT_CONNECTIONS',
        'TOTAL_CONNECTIONS',
        'USER',
        'account_type',
        'address',
        'bank_payment',
        'business_uid',
        'city',
        'country',
        'country_code',
        'created_at',
        'currency',
        'demo',
        'email',
        'email_verified',
        'hit',
        'image',
        'lang',
        'last_login',
        'last_login_country',
        'layouts',
        'name',
        'parent_id',
        'password',
        'paymob_api',
        'paymob_card_id',
        'paymob_cash_id',
        'paymob_iframe_id',
        'paymob_kisko_id',
        'paymob_merchant_id',
        'paymob_mobile_id',
        'paymob_payment',
        'paypal_email',
        'paypal_payment',
        'paytabs_payment',
        'paytabs_profile_id',
        'paytabs_server_key',
        'phone',
        'postcode',
        'publish_key',
        'role',
        'rule_id',
        'secret_key',
        'slug',
        'state',
        'status',
        'stripe_payment',
        'thumb',
        'title',
        'trial_expire',
        'user_name',
        'user_type',
        'verify_code',
    ];
}
