<input type="hidden" class="msg_opps" value="<?php echo helper_trans('oops'); ?>">
<input type="hidden" class="msg_error" value="<?php echo helper_trans('error'); ?>">
<input type="hidden" class="msg_success" value="<?php echo helper_trans('success'); ?>">
<input type="hidden" class="msg_sorry" value="<?php echo helper_trans('sorry'); ?>">
<input type="hidden" class="msg_yes" value="<?php echo helper_trans('yes'); ?>">
<input type="hidden" class="msg_cancel" value="<?php echo helper_trans('cancel'); ?>">
<input type="hidden" class="msg_convert" value="<?php echo helper_trans('convert'); ?>">
<input type="hidden" class="msg_congratulations" value="<?php echo helper_trans('congratulations'); ?>">
<input type="hidden" class="msg_send_successfully" value="<?php echo helper_trans('send-successfully'); ?>">
<input type="hidden" class="msg_setup_successfully" value="<?php echo helper_trans('setup-successfully'); ?>">
<input type="hidden" class="msg_something_wrong" value="<?php echo helper_trans('something-wrong'); ?>">
<input type="hidden" class="msg_try_again" value="<?php echo helper_trans('try-again'); ?>">
<input type="hidden" class="msg_valid_user_msg" value="<?php echo helper_trans('valid-user-msg'); ?>">
<input type="hidden" class="msg_password_reset_msg" value="<?php echo helper_trans('password-reset-msg'); ?>">
<input type="hidden" class="msg_password_reset_success_msg" value="<?php echo helper_trans('password-reset-success-msg'); ?>">
<input type="hidden" class="msg_confirm_pass_not_match_msg" value="<?php echo helper_trans('confirm-pass-not-match-msg'); ?>">
<input type="hidden" class="msg_old_password_doesnt_match" value="<?php echo helper_trans('old-password-doesnt-match'); ?>">
<input type="hidden" class="msg_inserted" value="<?php echo helper_trans('msg-inserted'); ?>">


<input type="hidden" class="msg_are_you_sure" value="<?php echo helper_trans('are-you-sure'); ?>">
<input type="hidden" class="msg_applied_successfully" value="<?php echo helper_trans('applied-successfully'); ?>">
<input type="hidden" class="msg_stop_recurring" value="<?php echo helper_trans('stop-this-recurring-invoice'); ?>">
<input type="hidden" class="msg_convert_estimate_to_draft_invoice" value="<?php echo helper_trans('convert-estimate-to-draft-invoice'); ?>">
<input type="hidden" class="msg_convert" value="<?php echo helper_trans('convert'); ?>">
<input type="hidden" class="msg_converted_successfully" value="<?php echo helper_trans('converted-successfully'); ?>">
<input type="hidden" class="msg_data_limit_over" value="<?php echo helper_trans('data-limit-over'); ?>">
<input type="hidden" class="msg_sending_failed" value="<?php echo helper_trans('sending-failed'); ?>">
<input type="hidden" class="msg_approved_successfully" value="<?php echo helper_trans('approved-successfully'); ?>">
<input type="hidden" class="msg_not_recover_file" value="<?php echo helper_trans('not-recover-file'); ?>">
<input type="hidden" class="msg_deleted_successfully" value="<?php echo helper_trans('deleted-successfully'); ?>">
<input type="hidden" class="msg_approve_this_invoice" value="<?php echo helper_trans('approve-this-invoice'); ?>">
<input type="hidden" class="msg_set_as_your_primary_business" value="<?php echo helper_trans('set-as-your-primary-business'); ?>">
<input type="hidden" class="msg_want_to_set" value="<?php echo helper_trans('want-to-set'); ?>">
<input type="hidden" class="msg_as_your_default_business" value="<?php echo helper_trans('as-your-default-business'); ?>">
<input type="hidden" class="msg_made_changes_not_saved" value="<?php echo helper_trans('made-changes-not-saved'); ?>">
<input type="hidden" class="msg_no_data_founds" value="<?php echo helper_trans('no-data-founds'); ?>">
<input type="hidden" class="msg_del_success" value="<?php echo helper_trans('deleted-successfully'); ?>">
<input type="hidden" class="msg_account_suspend_msg" value="<?php echo helper_trans('account-suspend-msg'); ?>">
<input type="hidden" class="msg_recurring_date" value="<?php echo helper_trans('recurring-date-msg'); ?>">
<input type="hidden" class="msg_convert_recurring" value="<?php echo helper_trans('convert-recurring-msg'); ?>">